User 기능 개발
BCSDLab/HANAL_BACK_END pull request #1
Opened 2022-08-14 06:29 UTC by YunYongWoon

- 회원가입
- 회원가입시 인증메일 전송, 코드 인증
- 로그인
- 로그아웃
- 비밀번호 찾기 시 메일 전송, 임시 비밀번호 전송
- 내정보
- 비밀번호 변경
- 학과/학년 변경

2022-08-14 17:42 UTC, knight7024 requested changes
일단 중요한 것들 위주로 코드 리뷰 진행했음

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/controller/UserController.java
> +    @PostMapping("me/password")
URL Mapping 잘못됨

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/controller/UserController.java
> +    @PostMapping("/me/department")
무언가를 수정하는 API는 REST적으로 PUT과 PATCH Method가 올바름.

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/enums/Department.java
> +public enum Department {
리눅스에서 문제 없는지 확인 필요

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/enums/UserType.java
> +public enum UserType {
권한을 대소비교로 한다면 나중에 중간 권한을 추가해야 할 상황이 생겼을 때 처리는 어떻게?

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        if (request.getGrade() < 1 || request.getGrade() > 4) {
BeanValidation에서 처리 가능

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        try {
Enum 검증도 BeanValidation에서 처리 가능
[[참고]](https://www.baeldung.com/javax-validations-enums)

변환도 MapStruct에서 처리 가능

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        user.setPassword(BCrypt.hashpw(request.getPassword(), BCrypt.gensalt()));
둘 다 default로 입력할 거면 MapStruct에서 처리 가능

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        if (!user.getIsAuth()) {
에러를 반환하지 않음

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        Optional<String> refreshTokenOptional = Optional.ofNullable(
key로 불러오지 않고 있음. 커밋 전에는 로컬 테스트 필수

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        String key = String.format("user:%s:refresh", user.getAccountId());
토큰 발행을 user_id로 했는데 왜 account_id로 조회?

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        String refreshToken = operations.get(key);
불필요한 연산. 바로 삭제해도 무방

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        String key = String.format("user:%s:refresh", user.getAccountId());
토큰 발행을 user_id로 했는데 왜 account_id로 조회?

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        mailUtil.sendAuthCodeMail(user, authNum);
순서가 인증번호를 저장하고 메일을 전송해야 db에서 지연이 발생했을 때 문제가 없음

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        userRepository.updatePassword(user);
순서 위와 마찬가지로 저장 후 메일 전송

2022-08-14 17:42 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        return jwtUtil.getDecodedJWT(token.substring(7));
null-safe한가?

2022-08-15 02:38 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/controller/UserController.java
> +    @PostMapping("me/password")
Put으로 수정

2022-08-15 02:39 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/controller/UserController.java
> +    @PostMapping("/me/department")
Put으로 수정

2022-08-15 02:40 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        mailUtil.sendAuthCodeMail(user, authNum);
순서 변경함

2022-08-15 02:40 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        userRepository.updatePassword(user);
순서 변경함

2022-08-15 02:41 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        return jwtUtil.getDecodedJWT(token.substring(7));
AuthInterceptor에서 사용하던 null체크를 함수로 빼서 같이 사용하도록 바꿈

2022-08-15 02:41 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        Optional<String> refreshTokenOptional = Optional.ofNullable(
변경 완료

2022-08-15 03:51 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        if (!user.getIsAuth()) {
예외를 반환하도록 변경함

2022-08-15 03:52 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        String key = String.format("user:%s:refresh", user.getAccountId());
토큰발행과 redis 저장 둘다 동일하게 User의 id값으로 저장하도록 변경함

2022-08-15 04:40 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        String key = String.format("user:%s:refresh", user.getAccountId());
위에서와 마찬가지로 user_id로 통일

2022-08-15 05:19 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        if (request.getGrade() < 1 || request.getGrade() > 4) {
BeanValidation에서 @Min, @Max로 처리함

2022-08-15 05:25 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        String refreshToken = operations.get(key);
redis에 저장되어있지 않더라도 그냥 delete 해버리고 결과 return 하면 된다는 뜻임?

2022-08-15 05:28 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/enums/Department.java
> +public enum Department {
어떤 문제가 생기는지 모르겠습니다. 검색해볼만한 키워드 부탁드립니다 ㅜ

2022-08-15 05:29 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        user.setPassword(BCrypt.hashpw(request.getPassword(), BCrypt.gensalt()));
user.setPassword(BCrypt.hashpw(request.getPassword(), BCrypt.gensalt())); 를 MapStruct의 expression으로 처리하라는건지?

2022-08-15 08:06 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        user.setPassword(BCrypt.hashpw(request.getPassword(), BCrypt.gensalt()));
expression, constant 사용해서 MapStruct에서 처리함

2022-08-15 13:34 UTC, knight7024 commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        String refreshToken = operations.get(key);
delete 함수의 반환 타입은 bool로 성공 여부를 알려줌. 따로 예외를 반환하지 않기도 하고, 로그아웃 했는데 예외가 발생하는 것도 이상하기 때문에 따로 처리할 필요 없다는 것

2022-08-15 14:18 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/enums/Department.java
> +public enum Department {
문제없음

2022-08-16 12:17 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/enums/UserType.java
> +public enum UserType {
추후 변경 예정

2022-08-16 12:18 UTC, YunYongWoon commented on src/main/java/com/bcsdlab/biseo/serviceImpl/UserServiceImpl.java
> +        try {
Enum 검증은 별도 Validator 생성하여 검증함. 다른 Enum값도 추후 사용 가능할듯.

변환은 MapStruct에서 처리함.

2022-08-16 12:48 UTC, merged